image:
  name: docker/compose:1.24.1
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375

before_script:
  - docker version
  - docker-compose version

stages:
- build
- test

build-image:
  stage: build
  script:
    - docker-compose -f docker-compose.development.yml build
  only:
    - development

test-image:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml run --rm app bash -c "bundle exec rake db:migrate db:seed RAILS_ENV=test && rails test RAILS_ENV=test"
  only:
    - development
