image:
  name: docker/compose:1.24.1
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375

before_script:
  - docker version
  - docker-compose version

stages:
- build
- test

build-image:
  stage: build
  script:
    - docker-compose down -v
    - docker-compose up --build

test-image:
  stage: test
  script:
    - docker-compose -f docker-compose.development.yml run --rm app bash -c "bundle exec rake db:setup db:migrate db:seed RAILS_ENV=test && rails test"
