version: '3.1'
volumes:
  bundle_cache: {}
  scrapy_shared:
services:
  app:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - api
      - search
    volumes:
      - scrapy_shared:/var/www/scrapy/data
      - bundle_cache:/bundle
      - .:/web
    environment:
      RAILS_SERVE_STATIC_FILES: 'true'
      PGHOST: db
      PGUSER: postgres
      AWS_ACCESS_KEY_ID: REMOVED
      AWS_SECRET_ACCESS_KEY: REMOVED
      AWS_BUCKET: alegreme-event-cover
      API_URL: http://api
      ELASTICSEARCH_URL: http://search:9200
      IS_DOCKER: 'true'
    links:
      - api
      - search
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    ports:
      - 5432:5432
  web:
    build:
      context: ./web
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
  api:
    build:
      context: ./ml
      dockerfile: ./Dockerfile
    ports:
        - "5000:5000"
    volumes:
        - /var/www/api/data
  bot:
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    ports:
        - "3030:3030"
    volumes:
        - /var/www/bot/data
  search:
    build:
      context: ./search
      dockerfile: ./Dockerfile
    environment:
      discovery.type: single-node
    ports:
        - "9200:9200"
    volumes:
        - /var/www/search/data
  scrapy:
    build:
      context: ./scrapy
      dockerfile: ./Dockerfile
    environment:
        SPLASH_URL: http://splash:8050
        IS_DOCKER: 'true'
    depends_on:
      - splash
    volumes:
        - scrapy_shared:/var/www/scrapy/data
    ports:
      - "7654:7654"
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
      - "5023:5023"

