version: '3.1'
volumes:
  bundle_cache: {}
services:
  app:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - api
      - search
    volumes:
      - bundle_cache:/bundle
      - .:/web
    environment:
      RAILS_SERVE_STATIC_FILES: 'true'
      PGHOST: db
      PGUSER: postgres
      AWS_ACCESS_KEY_ID: REMOVED
      AWS_SECRET_ACCESS_KEY: REMOVED
      AWS_BUCKET: alegreme-event-cover
      API_URL: http://api
      ELASTICSEARCH_URL: http://search:9200
    links:
      - api
      - search
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
    ports:
      - 5432:5432
  web:
    build:
      context: ./web
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
  api:
    build:
      context: ./ml
      dockerfile: ./Dockerfile
    ports:
        - "5000:5000"
    volumes:
        - /var/lib/api/data
  search:
    build:
      context: ./search
      dockerfile: ./Dockerfile
    environment:
      discovery.type: single-node
    ports:
        - "9200:9200"
    volumes:
        - /var/lib/search/data

