version: "3"
services: 
  label-studio:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    volumes: 
      - ./project:/label-studio/project
      - ./ml_backend:/label-studio/ml_backend
    restart: always