version: '2.3'
volumes:
  scrapy_data:
  splash_data:
services:
  scrapy:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SPLASH_URL: http://splash:8050
      IS_DOCKER: 'true'
      ENV: 'production'
      PRIVATE_IP: '10.136.227.110'
      PUBLIC_IP: '159.89.84.18'
      DOMAIN: 'www.alegreme.com'
    depends_on:
      - splash
    volumes:
      - ./alegreme:/var/www/scrapy/alegreme
      - ./data:/var/www/scrapy/data
      - ../logs/scrapy:/var/www/scrapy/log
    ports:
      - "7654:7654"
    restart: on-failure
    mem_limit: 2gb
  splash:
    image: scrapinghub/splash
    ports:
      - 8050:8050
      - 5023:5023
    restart: on-failure
    volumes:
      - splash_data:/var/www/splash/data
    mem_limit: 4gb
    mem_reservation: 256m
    command: --maxrss 4048 --max-timeout 600 --disable-lua-sandbox
