development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: app_development

test:
  adapter: test
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: app_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: app_production
