# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5
  timeout: 5000
  username: <%= Rails.application.credentials[Rails.env.to_sym][:db_user] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db_password] %>
development:
  <<: *default
  database: development

production:
  <<: *default
  database: production

test:
  <<: *default
  database: test
