# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= Rails.application.credentials[Rails.env.to_sym][:db_user] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db_password] %>
  host: db
  database: production

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= Rails.application.credentials[Rails.env.to_sym][:db_user] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db_password] %>
  database: development
  host: db
#  url: postgres://postgres:docker@localhost:5432/db

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= Rails.application.credentials[Rails.env.to_sym][:db_user] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db_password] %>
  database: test
#  url: postgres://postgres:docker@localhost:5432/db
  host: db
