meta_title: "Alegreme - Aproveite a cidade de Porto Alegre"
meta_description: "Atividades culturais, meetups, shows, rolês, feiras de rua, aquele filme no Mario Quintana... Um feed para quem quer explorar a cidade e não perder o que já conhece"
meta_image: "welcome/social-banner.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@portoalegreme"