meta_title: "Alegreme: Eventos e Cinema em Porto Alegre"
meta_description: "Eventos, shows, festas e cinema em Porto Alegre. Tudo que acontece em Porto Alegre!"
meta_image: "media/images/social-banner.png"
twitter_account: "@portoalegreme"
