source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '6.0.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'mini_racer', platforms: :ruby

gem 'rake', '13.0.3'
# gem "jsonb_accessor", "~> 1.1.0"

# Calendar
# gem "simple_calendar", "~> 2.0"

# Materialize
# gem 'materialize-sass', '~> 1.0.0'

gem 'friendly_id', '~> 5.2.4'

# Push Notifications
gem 'rpush'

# Devise
gem 'devise', github: 'heartcombo/devise', branch: 'ca-omniauth-2'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'
gem 'recaptcha'

gem 'lupa', git: 'https://github.com/edelpero/lupa.git'

gem 'jsonl'

gem 'geocoder'

gem 'gon'

gem 'picture_tag'

# Webpacker
gem 'webpacker', github: 'rails/webpacker', branch: 'master'

gem "browser", require: "browser/browser"

# Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 5.0.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# gem 'turbolinks', '~> 5.2.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.11'
# Use Redis adapter to run Action Cable in production

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Search
gem 'searchkick'
gem 'oj'
gem 'typhoeus'

# Graph
gem 'chartkick'
gem 'groupdate'

gem 'httparty'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# gem 'mini_magick'

gem 'image_processing', '~> 1.12'
# gem 'image_optim'
# gem 'image_optim_pack'

gem 'rack-cors'

gem 'shrine'
gem 'mimemagic'
gem 'shrine-color'

gem 'colorize'

gem 'facets', require: false

gem 'clockwork', require: false
gem 'daemons'

gem 'sitemap_generator'

gem 'pagy', '~> 3.5'

# gem 'active_record_extended'

gem 'rack-attack'

gem 'stimulus_reflex', '~> 3.4.1'
gem 'view_component', require: 'view_component/engine'
gem 'view_component_reflex'
# gem 'view_component_reflex', path: '/var/www/alegreme/gems/view_component_reflex', group: :development

group :production do
	gem 'aws-sdk-s3'
	gem 'sentry-raven'

	# Cache
	# gem 'dalli'
	gem 'connection_pool'

	# Sidekiq
	gem 'sidekiq'
	gem 'sidekiq-scheduler'
	gem 'sidekiq-unique-jobs'
	gem 'sinatra', require: nil
end

group :development, :production do
	gem "redis", ">= 4.0", :require => ["redis", "redis/connection/hiredis"]
	gem "hiredis"
	gem 'sendgrid-ruby'
end

group :development, :test do
	# Call 'byebug' anywhere in the code to stop execution and get a debugger console
	gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
	gem 'dotenv-rails'
	gem 'timecop'
end

group :development do
	# Access an interactive console on exception pages or by calling 'console' anywhere in the code.
	gem 'web-console', '>= 4.1.0'
	# Display performance information such as SQL time and flame graphs for each request in your browser.
	# Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
	gem 'rack-mini-profiler', '~> 2.0'
	gem 'listen', '~> 3.3'
	# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
	gem 'spring'
	# gem 'spring-watcher-listen', '~> 2.0.0'
	gem 'awesome_print', require: 'ap'
	gem 'niceql'
	# gem 'active_record_doctor'
	# gem 'bullet'
end

group :test do
	# Adds support for Capybara system testing and selenium driver
	gem 'capybara', '>= 2.15'
	gem 'selenium-webdriver'
	# Easy installation and use of chromedriver to run system tests with Chrome
	gem 'webdrivers'
	gem 'factory_bot_rails'
	gem 'database_cleaner'
	gem 'minitest'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
